// Default fair-housing rules (M14 layer 1). Editable per workspace in Settings.
// Screening aid, not legal advice.

export const FAIR_HOUSING_RULES = [
  {
    pattern: String.raw`\b(no|without) (kids|children)\b`,
    category: "familial_status",
    severity: "block",
    explanation: "Excludes families with children.",
    saferRewrite: "Describe the unit, not who should live in it.",
  },
  {
    pattern: String.raw`\badults?[- ]only\b`,
    category: "familial_status",
    severity: "block",
    explanation: "Excludes families with children.",
    saferRewrite: "Describe the unit, not who should live in it.",
  },
  {
    pattern: String.raw`\bperfect for (singles|a single person|couples)\b`,
    category: "familial_status",
    severity: "warn",
    explanation: "Signals a preferred household type.",
    saferRewrite: "Great for anyone who wants a quiet one-bedroom.",
  },
  {
    pattern: String.raw`\bideal for (young )?professionals\b|\byoung professionals\b`,
    category: "age",
    severity: "warn",
    explanation: "Signals an age or familial preference.",
    saferRewrite: "Close to transit and downtown offices.",
  },
  {
    pattern: String.raw`\bno section[- ]?8\b|\bsection[- ]?8 not accepted\b`,
    category: "source_of_income",
    severity: "block",
    explanation: "Source of income is protected in NY State, NYC and NJ.",
    saferRewrite: "All lawful sources of income are considered.",
  },
  {
    pattern: String.raw`\b(no|not accepting) (vouchers|housing vouchers|programs|assistance)\b`,
    category: "source_of_income",
    severity: "block",
    explanation: "Source of income is protected in NY State, NYC and NJ.",
    saferRewrite: "All lawful sources of income are considered.",
  },
  {
    pattern: String.raw`\bmust (have|show) (a )?(job|employment|paycheck)\b|\bemployed only\b`,
    category: "source_of_income",
    severity: "warn",
    explanation: "Can exclude people with lawful non-wage income.",
    saferRewrite: "Applicants must show the ability to pay rent from any lawful source.",
  },
  {
    pattern: String.raw`\benglish[- ]only\b|\bmust speak english\b`,
    category: "national_origin",
    severity: "block",
    explanation: "National origin is a protected class.",
    saferRewrite: "Remove the language requirement.",
  },
  {
    pattern: String.raw`\bable[- ]bodied\b|\bno wheelchairs?\b`,
    category: "disability",
    severity: "block",
    explanation: "Disability is a protected class.",
    saferRewrite: "Describe access features, e.g. 'third-floor walk-up'.",
  },
  {
    pattern: String.raw`\bno (pets|animals)\b(?!.*assistance animals)`,
    category: "disability",
    severity: "warn",
    explanation: "Assistance animals are not pets and must be considered.",
    saferRewrite: "No pets; assistance animals are welcome.",
  },
  {
    pattern: String.raw`\b(christian|muslim|jewish|catholic) (home|household|tenants?)\b`,
    category: "religion",
    severity: "block",
    explanation: "Religion is a protected class.",
    saferRewrite: "Describe the unit, not who should live in it.",
  },
  {
    pattern: String.raw`\bmature (tenants?|persons?|adults?)\b`,
    category: "age",
    severity: "warn",
    explanation: "Signals an age preference.",
    saferRewrite: "Quiet building.",
  },
  {
    pattern: String.raw`\b(section[- ]?8|vouchers?|programs?) (is |are )?not (accepted|welcome|taken)\b`,
    category: "source_of_income",
    severity: "block",
    explanation: "Source of income is protected in NY State, NYC and NJ.",
    saferRewrite: "All lawful sources of income are considered.",
  },
  {
    pattern: String.raw`\bno (city ?fheps|fheps|hra|dss|hasa|seps|linc|srap|nj ?rap|rap|welfare|ssi|ssdi|(government|public|rental) assistance|subsid(y|ies))\b`,
    category: "source_of_income",
    severity: "block",
    explanation: "NY and NJ protect vouchers, public assistance and benefits as lawful income.",
    saferRewrite: "All lawful sources of income are considered.",
  },
  {
    pattern: String.raw`\bvoucher holders? (need not|should not|don't) apply\b`,
    category: "source_of_income",
    severity: "block",
    explanation: "Source of income is protected in NY State, NYC and NJ.",
    saferRewrite: "All lawful sources of income are considered.",
  },
  {
    pattern: String.raw`\bincome (must|has to) (be|come) (from )?(employment|a job|w-?2|wages)\b`,
    category: "source_of_income",
    severity: "warn",
    explanation: "Can exclude people with lawful non-wage income.",
    saferRewrite: "Applicants must show the ability to pay rent from any lawful source.",
  },
] as const;
